# NeON build file (http://github.com/c4s4/neon)

extends:
- c4s4/build/buildir.yml
- c4s4/build/release.yml

default: archive

properties:
  NAME: 'goactivate'

targets:

  archive:
    depends: clean
    steps:
    - mkdir: =BUILD_DIR
    - tar:     '*'
      exclude: ['build.yml', '={BUILD_DIR}/**/*', '.*']
      prefix:  =NAME
      tofile:  '={BUILD_DIR}/={NAME}-={VERSION}.tar.gz'
