# NeON build file (http://github.com/c4s4/neon)

extends:
- c4s4/build/buildir.yml
- c4s4/build/changelog.yml

default: archive

properties:
  NAME:      "goactivate"

targets:

  archive:
    depends: clean
    steps:
    - mkdir: "#{BUILD_DIR}/#{NAME}-#{VERSION}"
    - "md2pdf README.md && mv README.pdf #{BUILD_DIR}/#{NAME}-#{VERSION}/"
    - "cp goactivate LICENSE.txt CHANGELOG.yml #{BUILD_DIR}/#{NAME}-#{VERSION}/"
    - "cd #{BUILD_DIR} && zip -r #{NAME}-#{VERSION}.zip #{NAME}-#{VERSION}/"
